language: ruby
rvm:
  - "2.0.0"

script:
  - bundle exec rake db:test:prepare
  - RAILS_ENV=test bundle exec rake

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
